default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: postgres
  password: 123456

test:
  <<: *default
  database: warriors_test

development:
  <<: *default
  database: warriors_dev

production:
  <<: *default
  database: warriors_prod